version: "3"
services:
  web:
    image: canals/php
    container_name: api.lbs.local
    environment:
      - VHOST_HOSTNAME=api.lbs.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "10880:80"
      - "10843:443"
#    env_file:
 #     - ./webenv.env
    volumes :
      - ./api:/var/www/api
      - ./src:/var/www/src
#      - ./html:/var/www/html
#      - ./data:/var/www/data
    links :
      - mysql:db
#      - mongo:mongo
#      - mail:mail
#      - postgres:pg

#############################
# mysql + adminer / can be replaced by mariadb
#############################
  mysql:
#    image: mysql:5.6
    image: mariadb:latest
    container_name: mysql.lbs.local
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=lbs
      - MYSQL_PASSWORD=lbs
      - MYSQL_DATABASE=lbs
    ports:
      - "3663:3306"
    volumes :
      - ./sql:/var/sql

  adminer:
     image: adminer
     container_name: adminer.lbs.local
     ports:
       - "8090:8080"
     links:
       - mysql:db



##############################################
# A second php service
##############################################

#  api:
#      image: canals/php
#      container_name: api
##      environment:
#       - VHOST_HOSTNAME=api.local
#       - VHOST_DOCROOT=/var/www/api
#     ports:
#       - "6080:80"
#       - "6443:443"
#     volumes :
#       - ./api:/var/www/api
#       - ./src:/var/www/src
#       - ./html:/var/www/html
#     links :
#        - mysql:db

##################################
# postgres + adminer
###################################
# postgres:
#   image: postgres
#   container_name: postgres.local
#   environment :
#     - POSTGRES_PASSWORD = pgroot
#     - POSTGRES_USER = pguser
#   ports:
#     - "5432:5432"

# adminer-pg:
#   image: adminer
#   container_name: adminer_pg.dev.local
#   ports:
#     - "8088:8080"
#   links:
#     - postgres:db
#

################################################
# mongodb & mongo-express
###############################################
## mongo:
#   image: mongo:3.4
#   container_name: mongo.dev.local
#   ports:
#       - 27017:27017

# mongo-express:
#      image: mongo-express:latest
#      container_name: mongo_express.dev.local
#      ports:
#        - "8081:8081"
#      links:
#        - mongo:mongo

##############################################
# mailcatcher
##############################################
## mail:
#    image: schickling/mailcatcher
#    container_name: mail.dev.local
#    ports:
#      - "1080:1080"

########################################
# shared storage : useful for, e.g. sharing
#   uploaded documents (img, others) between multiple services
########################################
volumes:
   data:
